include: package:lints/recommended.yaml

analyzer:
  exclude:
    - test/crypto/openssl.dart
  language:
    strict-casts: true

formatter:
  line_length: 80

linter:
  rules:
    - prefer_double_quotes
    - camel_case_types
