name: scp03
description: A SCP03(GlobalPlatform Technology Secure Channel Protocol '03') implementation in Dart
version: 1.0.0
repository: https://github.com/scenee/scp03_dart

environment:
  sdk: ^3.6.0

dependencies:
  ffi: ^2.1.3
  ffi_assist: ^0.1.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
  ffigen: ^16.0.0

# The generated code is used only for testing
ffigen:
  output: 'test/crypto/openssl.dart'
  name: 'OpenSSL'
  # You have to specify the path to the header files of the C library you want to bind.
  compiler-opts:
    - '-I/opt/local/libexec/openssl3/include/'
  headers:
    entry-points:
      - '/opt/local/libexec/openssl3/include/openssl/bn.h'
      - '/opt/local/libexec/openssl3/include/openssl//core_names.h'
      - '/opt/local/libexec/openssl3/include/openssl/evp.h'
      - '/opt/local/libexec/openssl3/include/openssl/ec.h'
      - '/opt/local/libexec/openssl3/include/openssl/kdf.h'
